#!/usr/bin/env python3
"""Generate `notes/test-inventory.md` — every test, its tier, and the risk it covers.

Generated rather than hand-written for one reason: a 109-row table maintained by
hand is a table that is wrong within a week. Read from the source with `ast`, so
`make inventory` always matches what pytest would collect.
"""

from __future__ import annotations

import ast
import re
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent
RISK = re.compile(r"\bR\d{1,2}\b")
LAYERS = ["unit", "contract", "api", "e2e", "perf", "ui"]


def tier_of(node: ast.FunctionDef | ast.AsyncFunctionDef) -> str:
    for decorator in node.decorator_list:
        name = ast.unparse(decorator)
        if match := re.fullmatch(r"pytest\.mark\.(p[012])", name):
            return match.group(1).upper()
    return "—"


def cases(path: Path) -> list[tuple[str, str, str, str]]:
    """(tier, name, risks, summary) for every test in one file."""
    tree = ast.parse(path.read_text(encoding="utf-8"))
    module_risks = RISK.findall(ast.get_docstring(tree) or "")
    found = []
    for node in tree.body:
        if not isinstance(node, ast.FunctionDef | ast.AsyncFunctionDef):
            continue
        if not node.name.startswith("test_"):
            continue
        doc = ast.get_docstring(node) or ""
        summary = doc.splitlines()[0] if doc else ""
        # Strip the leading risk prefix ("R2:", "R16/R6:", "R7 / dead code:") — the
        # risk already has its own column.
        summary = re.sub(r"^R\d{1,2}\b[^:]*:\s*", "", summary)
        risks = list(dict.fromkeys(RISK.findall(doc))) or list(dict.fromkeys(module_risks))
        found.append(
            (
                tier_of(node),
                node.name,
                ", ".join(risks[:3]) or "—",
                summary.rstrip("."),
            )
        )
    return found


def main() -> int:
    files = sorted(
        (REPO_ROOT / "tests").rglob("test_*.py"),
        key=lambda p: (LAYERS.index(p.parent.name) if p.parent.name in LAYERS else 9, p.name),
    )
    total = sum(len(cases(f)) for f in files)
    tier_counts: dict[str, int] = {}
    for f in files:
        for tier, *_ in cases(f):
            tier_counts[tier] = tier_counts.get(tier, 0) + 1

    lines = [
        "# Test inventory",
        "",
        f"{total} test functions. Parametrized ones expand further at collection time —",
        "`pytest --collect-only -q` reports 109 collected tests in total.",
        "",
        "Generated by `make inventory`; do not edit by hand. Tier definitions are in",
        "`TEST_STRATEGY.md`, risk IDs in `risk-register.md`.",
        "",
        "| Tier | Tests |",
        "|---|---|",
    ]
    lines += [f"| **{tier}** | {tier_counts[tier]} |" for tier in sorted(tier_counts)]

    for path in files:
        rows = cases(path)
        rel = path.relative_to(REPO_ROOT)
        lines += [
            "",
            f"## `{rel}`",
            "",
            f"{len(rows)} tests.",
            "",
            "| Tier | Test | Risk | Covers |",
            "|---|---|---|---|",
        ]
        for tier, name, risks, summary in rows:
            lines.append(f"| {tier} | `{name}` | {risks} | {summary} |")

    out = REPO_ROOT / "notes" / "test-inventory.md"
    out.write_text("\n".join(lines) + "\n", encoding="utf-8")
    print(f"{out}: {total} test functions across {len(files)} files")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
